services:
  chat-app-nginx:
    image: nginx:latest
    container_name: chat-app-nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - chat-app-backend1
      - chat-app-backend2
      - chat-app-frontend

  chat-app-backend1:
    image: chat-app-backend:latest
    container_name: chat-app-backend1
    ports:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://chat-app-db:3306/edu?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE: 300
      SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE: 100
      SPRING_RABBITMQ_HOST: chat-app-rabbitmq
      SPRING_RABBITMQ_AMQP-PORT: 5672
      SPRING_RABBITMQ_RELAY-PORT: 61613
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_RABBITMQ_HEALTHCHECK_EXCHANGE-NAME: healthcheck.exchange.1
      SPRING_DATA_REDIS_HOST: chat-app-redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_DURATION-MILLIS: 10000
      SPRING_ELASTICSEARCH_URIS: http://chat-app-es:9200
      SPRING_KAFKA_BOOTSTRAP-SERVERS: chat-app-kafka:9092

    depends_on:
      - chat-app-db
      - chat-app-rabbitmq
      - chat-app-redis
      - chat-app-es
      - chat-app-kafka
    restart: always

  chat-app-backend2:
    image: chat-app-backend:latest
    container_name: chat-app-backend2
    ports:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://chat-app-db:3306/edu?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE: 300
      SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE: 100
      SPRING_RABBITMQ_HOST: chat-app-rabbitmq
      SPRING_RABBITMQ_AMQP-PORT: 5672
      SPRING_RABBITMQ_RELAY-PORT: 61613
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_RABBITMQ_HEALTHCHECK_EXCHANGE-NAME: healthcheck.exchange.2
      SPRING_DATA_REDIS_HOST: chat-app-redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_DURATION-MILLIS: 10000
      SPRING_ELASTICSEARCH_URIS: http://chat-app-es:9200
      SPRING_KAFKA_BOOTSTRAP-SERVERS: chat-app-kafka:9092
    depends_on:
      - chat-app-db
      - chat-app-rabbitmq
      - chat-app-redis
      - chat-app-es
      - chat-app-kafka
    restart: always

  chat-app-rabbitmq:
    image: rabbitmq:3-management
    container_name: chat-app-rabbitmq
    ports:
      - "5672"
      - "15672:15672"
      - "61613"
    environment:
      RABBITMQ_STOMP_LISTEN_PORT: 61613
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_stomp && rabbitmq-server && rabbitmq_management && rabbitmq_event_exchange && rabbitmq_prometheus"

  chat-app-db:
    image: mysql:latest
    container_name: chat-app-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=edu

  chat-app-redis:
    image: redis:latest
    container_name: chat-app-redis
    ports:
      - "6379:6379"

  chat-app-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: chat-app-es
    environment:
      - node.name=es-node
      - cluster.name=search-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - 9200:9200 # https
      - 9300:9300 #tcp

  chat-app-zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: chat-app-zookeeper
    ports:
     - "2181:2181"

  chat-app-kafka:
    image: wurstmeister/kafka:latest
    container_name: chat-app-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: chat-app-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092  # Kafka 브로커가 대기할 인터페이스 설정
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://chat-app-kafka:9092  # 외부 클라이언트가 접근할 Kafka 브로커 주소
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - chat-app-zookeeper

  chat-app-frontend:
    image: chat-app-frontend:latest
    container_name: chat-app-frontend
    ports:
      - "80"
    environment:
      - WDS_SOCKET_PORT=0


